framework:
    rate_limiter:
        # Limiter de connexion (3 tentatives par minute par IP)
        login_ip:
            policy: sliding_window
            limit: 2
            interval: '60 seconds'

        # Limiter par username (3 tentatives par minute par utilisateur)
        login_username:
            policy: sliding_window
            limit: 2
            interval: '60 seconds'

        # Limiter global (éviter les attaques massives)
        api_global:
            policy: token_bucket
            limit: 100
            rate: { amount: 100, interval: '60 seconds' }
