version: '3.8'

services:
  database:
    image: postgres:16-alpine
    container_name: assurbank_db_container
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: assurbank_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: assurbank_mailpit
    ports:
      - "56414:1025"  # Port SMTP
      - "56413:8025"  # Interface web
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  db_data: